apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../addons/sealed-secrets

patches:
  # Sealed Secrets
  - target:
      kind: Application
      name: sealed-secrets
      version: v1alpha1
    patch: |-
      - op: replace
        path: /spec/sources/0/targetRevision
        value: 2.14.2
  # Cert Manager
  - target:
      kind: Application
      name: cert-manager
      version: v1alpha1
    patch: |-
      - op: replace
        path: /spec/sources/0/targetRevision
        value: 'v1.13.3
  # External Secrets
  - target:
      kind: Application
      name: external-secrets
      version: v1alpha1
    patch: |-
      - op: replace
        path: /spec/sources/0/targetRevision
        value: 0.9.11