apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: 'v1.11.0'
    helm:
      releaseName: cert-manager
      valueFiles:
      - $values/cert-manager/values.yaml
  - repoURL: 'https://github.com/project0864/values.git'
    targetRevision: HEAD
    ref: values
  destination:
    namespace: cert-manager
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true